(ns issues.cli
  "Command-line entry point for the issues tracker.

  `run` takes the argument vector and returns a result map
  `{:exit int :kind kw :data any :warnings [str]}`; `-main` prints it and
  exits. Keeping `System/exit` out of `run` lets tests drive the CLI
  in-process."
  (:require [babashka.cli :as cli]
            [babashka.fs :as fs]
            [babashka.process :as process]
            [clojure.string :as str]
            [issues.analyze :as analyze]
            [issues.config :as config]
            [issues.discover :as discover]
            [issues.issue :as issue]
            [issues.project :as project]
            [issues.query :as query]
            [issues.render :as render]
            [issues.snapshot :as snapshot]
            [issues.store :as store]
            [issues.ui :as ui]))

;;;; Results and errors

(defn- ok
  ([kind data] (ok kind data nil))
  ([kind data warnings]
   (cond-> {:exit 0 :kind kind :data data}
     (seq warnings) (assoc :warnings (vec warnings)))))

(defn- fail
  "A user-facing error: exit 1 with MSG."
  [msg]
  (throw (ex-info msg {:issues/exit 1})))

;;;; Scope: which .issues/ directory a command acts on

(defn- load-cfg
  [opts]
  (:config (config/load-config (or (:config opts) (config/config-path)))))

(defn- start-dir
  [opts]
  (str (fs/absolutize (or (:dir opts) (fs/cwd)))))

(defn- resolve-scope
  "The project a command acts on: `--project ID` via discovery, else the
  nearest `.issues/` at or above `--dir` (default cwd)."
  [opts]
  (if-let [id (:project opts)]
    (let [p (discover/find-project (load-cfg opts) id)]
      {:root (:path p) :issues-dir (:issues-dir p) :id (:id p)})
    (let [start (start-dir opts)]
      (if-let [loc (project/locate start)]
        (assoc loc :id (project/project-id (:issues-dir loc)))
        (fail (str "not inside an .issues project: " start
                   "\nrun `issues init` there to create one"))))))

(defn- scope-issues
  "Every issue in scope: all projects when `--all`, else the resolved
  project. Returns `{:issues [...] :all? bool}`."
  [opts]
  (if (:all opts)
    {:issues (snapshot/all-issues (snapshot/build (load-cfg opts) {})) :all? true}
    {:issues (:issues (project/read-project (resolve-scope opts))) :all? false}))

(defn- after-mutation!
  "Regenerate the README index after a change. Returns warnings."
  [{:keys [issues-dir id]}]
  (let [{:keys [state]} (store/write-index! issues-dir id (store/read-all issues-dir))]
    (when (= :foreign state)
      ["README.md was not generated by issues and was left untouched"])))

(defn- find-or-fail
  [{:keys [issues-dir id]} n]
  (or (store/find-issue issues-dir n)
      (fail (str "no issue " n " in " id))))

(defn- with-ref
  [scope issue]
  (assoc issue :project (:id scope) :ref (issue/ref-string (:id scope) (:id issue))))

(defn- coerce-opt
  "Validate an enum-like option through `issue/coerce-field`, failing
  with the field's own message on bad input."
  [opts field]
  (when-some [v (get opts field)]
    (let [{:keys [value error]} (issue/coerce-field field (name v))]
      (when error (fail (str "--" (name field) ": " error)))
      value)))

(defn- set-field!
  "Apply FIELD := VALUE (a raw string) to issue N, bump updated, regenerate
  the index."
  [scope n field value]
  (let [{:keys [value error]} (issue/coerce-field field value)]
    (when error (fail (str (name field) ": " error)))
    (let [updated (store/update! (:issues-dir scope) n
                                 #(issue/assoc-field % field value (issue/today)))]
      (ok :updated (with-ref scope updated) (after-mutation! scope)))))

;;;; Commands

(def global-spec
  {:json {:coerce :boolean :desc "Output JSON"}
   :edn {:coerce :boolean :desc "Output EDN"}
   :dir {:alias :C :ref "<dir>" :desc "Act as if run from <dir>"}
   :all {:coerce :boolean :desc "Act on every discovered project"}
   :project {:ref "<id>" :desc "Act on the discovered project <id>"}
   :config {:ref "<path>" :desc "Config file (default ~/.config/issues/config.edn)"}
   :help {:alias :h :coerce :boolean :desc "Show help"}})

(def add-spec
  {:type {:ref "<type>" :desc "feature (default), bug, chore, idea"}
   :priority {:alias :p :ref "<pri>" :desc "p0..p3 (default p2)"}
   :tags {:ref "<a,b>" :desc "Comma-separated tags"}})

(def list-spec
  {:status {:ref "<status>"}
   :type {:ref "<type>"}
   :priority {:alias :p :ref "<pri>"}
   :tag {:ref "<tag>"}
   :closed {:coerce :boolean :desc "Include done and dropped"}})

(def usage
  (str/join
   "\n"
   ["issues - per-project issue tracker and cross-project control plane"
    ""
    "Usage: issues [global flags] <command> [args]"
    ""
    "Project commands (run inside a project, or with --dir/--project):"
    "  init [--id <id>]              Create .issues/ here"
    "  add <title...> [--type t] [-p p] [--tags a,b]"
    "                                File a request (status inbox)"
    "  list [--status s] [--type t] [-p p] [--tag t] [--closed]"
    "  show <id>                     Metadata plus details text"
    "  details <id>                  Create the details file if needed; print its path"
    "  edit <id>                     Open the details file in $EDITOR"
    "  set <id> <field> <value>      status, type, priority, title, tags, blocked-by, related"
    "  start | review | done | drop <id>"
    "  block <id> --on <n>           unblock <id> [--on <n>]"
    "  next                          Highest-priority unblocked ready issue"
    "  inbox                         Requests still to be fleshed out"
    "  index                         Regenerate .issues/README.md"
    "  doctor                        Report problems (exit 2 when any errors)"
    "  ui [--port n] [--no-open]     Serve a local board of this project's issues"
    ""
    "list, next, inbox and doctor accept --all to span every discovered project."
    ""
    "Control-plane commands (crawl the configured roots):"
    "  projects                      Discovered projects, candidates and shadowed copies"
    "  status [--all]                Issue counts per status"
    "  attention [--project id]      What needs Kira (review) and Claude (inbox, ready)"
    "  snapshot [--with-details]     The whole cross-project data value (EDN by default)"
    "  config                        Effective config and where it came from"
    "  analyze [--kind k] [--threshold x] [--include-closed] [--no-save] [--file p]"
    "                                Run analyzers over the snapshot; save insights"
    "  insights [--kind k] [--file p]"
    "                                Show saved insights"
    ""
    "Global flags:"
    (cli/format-opts {:spec global-spec})
    ""]))

(defn- cmd-help [_]
  (ok :message usage))

(defn- cmd-init [{:keys [opts]}]
  (let [root (start-dir opts)
        {:keys [created? issues-dir]} (project/init! root {:id (:id opts)})]
    (ok :message (str (if created? "initialized " "already initialized: ") issues-dir))))

(defn- cmd-add [{:keys [opts args]}]
  ;; Everything after `add` arrives unparsed so the title can be free text;
  ;; re-parse it here to pick up flags placed after the title.
  (let [{re-args :args re-opts :opts} (cli/parse-args args {:spec (merge global-spec add-spec)})
        opts (merge opts re-opts)
        title (str/trim (str/join " " re-args))
        scope (resolve-scope opts)
        _ (when (str/blank? title) (fail "add: a title is required"))
        fields {:title title
                :type (coerce-opt opts :type)
                :priority (coerce-opt opts :priority)
                :tags (some-> (:tags opts) (as-> t (:value (issue/coerce-field :tags t))))}
        created (store/create! (:issues-dir scope) fields (issue/today))]
    (ok :updated (with-ref scope created) (after-mutation! scope))))

(defn- cmd-list [{:keys [opts]}]
  (let [criteria {:status (coerce-opt opts :status)
                  :type (coerce-opt opts :type)
                  :priority (coerce-opt opts :priority)
                  :tag (:tag opts)}
        {:keys [issues all?]} (scope-issues opts)
        shown (cond->> (query/filter-issues issues criteria)
                (not (or (:closed opts) (:status opts))) (filter query/open?))]
    (ok :issue-list {:issues (query/sort-issues shown) :all? all?})))

(defn- cmd-show [{:keys [opts]}]
  (let [scope (resolve-scope opts)
        found (with-ref scope (find-or-fail scope (:id opts)))]
    (ok :issue (assoc found :details-text (store/read-details found)))))

(defn- cmd-details [{:keys [opts]}]
  (let [scope (resolve-scope opts)
        found (store/ensure-details! (find-or-fail scope (:id opts)))]
    (ok :message (store/details-path found) (after-mutation! scope))))

(defn- editor-command
  []
  (first (remove str/blank? [(System/getenv "VISUAL") (System/getenv "EDITOR") "vi"])))

(defn- cmd-edit [{:keys [opts]}]
  (let [scope (resolve-scope opts)
        found (store/ensure-details! (find-or-fail scope (:id opts)))
        path (store/details-path found)]
    ;; sh expands a multi-word $EDITOR while "$1" keeps the path intact.
    (process/shell {:inherit true} "sh" "-c" (str (editor-command) " \"$1\"") "issues" path)
    (ok :message path (after-mutation! scope))))

(defn- cmd-set [{:keys [opts]}]
  (let [{:keys [id field value]} opts]
    (when (nil? value) (fail "set: usage is `issues set <id> <field> <value>`"))
    (set-field! (resolve-scope opts) id field value)))

(defn- status-cmd
  [status]
  (fn [{:keys [opts]}]
    (set-field! (resolve-scope opts) (:id opts) :status status)))

(defn- cmd-block [{:keys [opts]}]
  (let [scope (resolve-scope opts)
        {:keys [id on]} opts]
    (when (= id on) (fail "an issue cannot block itself"))
    (find-or-fail scope on)
    (let [updated (store/update! (:issues-dir scope) id
                                 #(-> %
                                      (update :blocked-by (fnil conj #{}) on)
                                      (issue/assoc-field :status :blocked (issue/today))))]
      (ok :updated (with-ref scope updated) (after-mutation! scope)))))

(defn- cmd-unblock [{:keys [opts]}]
  (let [scope (resolve-scope opts)
        {:keys [id on]} opts
        unblock (fn [found]
                  (let [remaining (if on (disj (:blocked-by found) on) #{})
                        status (if (and (empty? remaining) (= :blocked (:status found)))
                                 :ready
                                 (:status found))]
                    (-> found
                        (assoc :blocked-by remaining)
                        (issue/assoc-field :status status (issue/today)))))
        updated (store/update! (:issues-dir scope) id unblock)]
    (ok :updated (with-ref scope updated) (after-mutation! scope))))

(defn- cmd-next [{:keys [opts]}]
  (let [{:keys [issues all?]} (scope-issues opts)]
    (ok :next {:issue (query/next-issue issues) :all? all?})))

(defn- cmd-inbox [{:keys [opts]}]
  (let [{:keys [issues all?]} (scope-issues opts)]
    (ok :issue-list {:issues (query/inbox issues) :all? all?})))

(defn- cmd-index [{:keys [opts]}]
  (let [{:keys [issues-dir id]} (resolve-scope opts)
        {:keys [written? state]} (store/write-index! issues-dir id (store/read-all issues-dir))]
    (case state
      :foreign (fail (str issues-dir "/README.md was not generated by issues; "
                          "remove it to let issues own it"))
      (ok :message (str issues-dir "/README.md " (if written? "written" "up to date"))))))

(defn- cmd-doctor [{:keys [opts]}]
  (let [problems (if (:all opts)
                   (snapshot/all-problems (snapshot/build (load-cfg opts) {}))
                   (let [scope (resolve-scope opts)]
                     (mapv #(assoc % :project (:id scope))
                           (:problems (project/read-project scope)))))
        errors? (some #(= :error (:severity %)) problems)]
    (assoc (ok :doctor {:problems problems}) :exit (if errors? 2 0))))

(defn- cmd-projects [{:keys [opts]}]
  (let [snap (snapshot/build (load-cfg opts) {})]
    (ok :projects
        {:projects (mapv (fn [p]
                           {:id (:id p) :path (:path p) :issues-dir (:issues-dir p)
                            :counts (query/counts (:issues p))
                            :problems (count (:problems p))})
                         (:projects snap))
         :candidates (:candidates snap)
         :shadowed (:shadowed snap)
         :warnings (:warnings snap)})))

(defn- cmd-status [{:keys [opts]}]
  (let [projects (if (:all opts)
                   (:projects (snapshot/build (load-cfg opts) {}))
                   [(project/read-project (resolve-scope opts))])]
    (ok :counts (mapv (fn [p] {:project (:id p) :counts (query/counts (:issues p))})
                      projects))))

(defn- cmd-attention [{:keys [opts]}]
  ;; Cross-project by default; --project narrows to one.
  (let [{:keys [issues]} (scope-issues (if (:project opts) opts (assoc opts :all true)))]
    (ok :attention (query/attention issues))))

(defn- cmd-snapshot [{:keys [opts]}]
  (ok :snapshot (snapshot/build (load-cfg opts) {:with-details? (:with-details opts)})))

(defn- cmd-config [{:keys [opts]}]
  (ok :config (config/load-config (or (:config opts) (config/config-path)))))

(defn- analyzer-kind
  [opts]
  (when-let [k (:kind opts)]
    (if (contains? (set analyze/kinds) k)
      k
      (fail (str "unknown analyzer " (name k) "; known: "
                 (str/join ", " (map name analyze/kinds)))))))

(defn- cmd-analyze [{:keys [opts]}]
  (let [kind (analyzer-kind opts)
        snap (snapshot/build (load-cfg opts) {})
        aopts {:threshold (or (:threshold opts) 0.5)
               :include-closed? (boolean (:include-closed opts))}
        insights (if kind
                   (analyze/analyze kind snap aopts)
                   (analyze/run-all snap aopts))
        path (or (:file opts) (analyze/insights-path))]
    (when-not (:no-save opts)
      (analyze/save-insights! path insights))
    (ok :insights insights)))

(defn- cmd-insights [{:keys [opts]}]
  (let [kind (analyzer-kind opts)
        insights (analyze/load-insights (or (:file opts) (analyze/insights-path)))]
    (ok :insights (cond->> insights
                    kind (filterv #(= kind (:analyzer %)))))))

(defn- cmd-ui [{:keys [opts]}]
  (let [load (if (:all opts)
               (let [cfg (load-cfg opts)]
                 (fn [] (:projects (snapshot/build cfg {}))))
               (let [scope (resolve-scope opts)]
                 (fn [] [(project/read-project scope)])))
        _ (load)
        {:keys [url]} (ui/start! {:load load :port (or (:port opts) 4477)})]
    (println "issues ui at" url "(Ctrl-C to stop)")
    (flush)
    (when-not (:no-open opts)
      (ui/open-browser! url))
    ;; Serve until interrupted; the process ends with the terminal's Ctrl-C.
    @(promise)))

(defn- cmd-unknown [{:keys [args]}]
  (if (seq args)
    (fail (str "unknown command " (pr-str (first args)) "\n\n" usage))
    (cmd-help nil)))

(def ^:private id-arg
  {:args->opts [:id] :coerce {:id :int} :require [:id]})

(def table
  [{:cmds ["help"] :fn cmd-help}
   {:cmds ["init"] :fn cmd-init :spec {:id {:ref "<id>"}}}
   {:cmds ["add"] :fn cmd-add}
   {:cmds ["list"] :fn cmd-list :spec list-spec}
   (merge {:cmds ["show"] :fn cmd-show} id-arg)
   (merge {:cmds ["details"] :fn cmd-details} id-arg)
   (merge {:cmds ["edit"] :fn cmd-edit} id-arg)
   {:cmds ["set"] :fn cmd-set :args->opts [:id :field :value]
    :coerce {:id :int :field :keyword} :require [:id :field]}
   (merge {:cmds ["start"] :fn (status-cmd "in-progress")} id-arg)
   (merge {:cmds ["review"] :fn (status-cmd "review")} id-arg)
   (merge {:cmds ["done"] :fn (status-cmd "done")} id-arg)
   (merge {:cmds ["drop"] :fn (status-cmd "dropped")} id-arg)
   (merge {:cmds ["block"] :fn cmd-block :spec {:on {:coerce :int :require true}}} id-arg)
   (merge {:cmds ["unblock"] :fn cmd-unblock :spec {:on {:coerce :int}}} id-arg)
   {:cmds ["next"] :fn cmd-next}
   {:cmds ["inbox"] :fn cmd-inbox}
   {:cmds ["index"] :fn cmd-index}
   {:cmds ["doctor"] :fn cmd-doctor}
   {:cmds ["ui"] :fn cmd-ui
    :spec {:port {:coerce :int :ref "<n>" :desc "Port (default 4477; 0 picks a free one)"}
           :no-open {:coerce :boolean :desc "Do not open the browser"}}}
   {:cmds ["projects"] :fn cmd-projects}
   {:cmds ["status"] :fn cmd-status}
   {:cmds ["attention"] :fn cmd-attention}
   {:cmds ["snapshot"] :fn cmd-snapshot :spec {:with-details {:coerce :boolean}}}
   {:cmds ["config"] :fn cmd-config}
   {:cmds ["analyze"] :fn cmd-analyze
    :spec {:kind {:coerce :keyword} :threshold {:coerce :double}
           :include-closed {:coerce :boolean} :no-save {:coerce :boolean}
           :file {:ref "<path>"}}}
   {:cmds ["insights"] :fn cmd-insights :spec {:kind {:coerce :keyword} :file {:ref "<path>"}}}
   {:cmds [] :fn cmd-unknown}])

;;;; Entry points

(defn- format-of
  [opts]
  (cond (:json opts) :json
        (:edn opts) :edn
        :else :human))

(defn run
  "Run the CLI with ARGS (a sequence of strings). Returns
  `{:exit int :kind kw :data any :warnings [str] :format kw}` and never
  calls `System/exit`."
  [args]
  (let [opts (atom {})
        capture (fn [f] (fn [m] (reset! opts (:opts m)) (f m)))
        table (mapv #(update % :fn capture) table)
        result (try
                 (if (some #{"-h" "--help"} (take-while #(str/starts-with? % "-") args))
                   (cmd-help nil)
                   (cli/dispatch table (vec args) {:spec global-spec}))
                 (catch clojure.lang.ExceptionInfo e
                   (let [data (ex-data e)]
                     (cond
                       (:issues/exit data)
                       {:exit (:issues/exit data) :kind :message :data (ex-message e)}

                       (= :org.babashka/cli (:type data))
                       {:exit 1 :kind :message :data (str "issues: " (ex-message e))}

                       :else (throw e)))))]
    (assoc result :format (format-of @opts))))

(defn -main [& args]
  (let [{:keys [exit warnings format] :as result} (run args)
        text (render/emit result format)]
    (doseq [w warnings]
      (binding [*out* *err*] (println "warning:" w)))
    (if (zero? exit)
      (print text)
      (binding [*out* *err*] (print text)))
    (flush)
    (System/exit exit)))
