(ns issues.project
  "Locating and reading a single project's `.issues/` directory: walking up
  the filesystem to find one, reading its `project.edn`, and assembling the
  full picture of its issues and problems.

  Every path taken or returned by a function here is a plain string, never
  a `java.nio.file.Path`."
  (:require [babashka.fs :as fs]
            [clojure.edn :as edn]
            [issues.issue :as issue]
            [issues.store :as store]))

(defn issues-dir?
  "True when DIR/.issues is a directory."
  [dir]
  (fs/directory? (fs/path dir ".issues")))

(defn locate
  "Walk up from START (default the current directory) through parent
  directories, returning the first one containing a `.issues` directory as
  `{:root <abs dir> :issues-dir <abs dir>/.issues}`. `nil` when no
  ancestor of START has one."
  ([] (locate (fs/cwd)))
  ([start]
   (loop [dir (fs/absolutize start)]
     (when dir
       (if (issues-dir? dir)
         {:root (str dir) :issues-dir (str (fs/path dir ".issues"))}
         (recur (fs/parent dir)))))))

(defn read-project-edn
  "The map in ISSUES-DIR/project.edn, or `{}` when the file is absent.
  Throws `ex-info` with `:issues/exit 1` when the file exists but can't be
  read as a map."
  [issues-dir]
  (let [path (str (fs/path issues-dir "project.edn"))]
    (if-not (fs/exists? path)
      {}
      (let [unreadable #(ex-info "unreadable project.edn" {:issues/exit 1 :file path})
            v (try
                (edn/read-string (slurp path))
                (catch Exception _ (throw (unreadable))))]
        (if (map? v)
          v
          (throw (unreadable)))))))

(defn project-id
  "The project id for ISSUES-DIR: `:id` from `read-project-edn` when
  present, otherwise the name of ISSUES-DIR's parent directory."
  [issues-dir]
  (or (:id (read-project-edn issues-dir))
      (str (fs/file-name (fs/parent (fs/path issues-dir))))))

(defn init!
  "Ensure ROOT is a project: create ROOT/.issues if it doesn't already
  exist, write `project.edn` with `:id` when ID is given and no
  `project.edn` exists yet, and (re)write the generated README index.
  Returns `{:created? bool :issues-dir <abs>}`, where `:created?` is true
  only when `.issues` was newly created by this call."
  [root {:keys [id]}]
  (let [root (str (fs/absolutize root))
        issues-dir (str (fs/path root ".issues"))
        created? (not (fs/directory? issues-dir))
        project-edn (str (fs/path issues-dir "project.edn"))]
    (fs/create-dirs issues-dir)
    (when (and id (not (fs/exists? project-edn)))
      (spit project-edn (str "{:id " (pr-str id) "}\n")))
    (store/write-index! issues-dir (project-id issues-dir) (store/read-all issues-dir))
    {:created? created? :issues-dir issues-dir}))

(defn- annotate-problem
  "PROBLEM from ISSUE's own `:problems`, with `:id` and `:file` filled in
  from ISSUE when not already present."
  [issue problem]
  (cond-> problem
    (not (contains? problem :id)) (assoc :id (:id issue))
    (not (contains? problem :file)) (assoc :file (:file issue))))

(defn- index-problem
  "The single index-related problem for ISSUES-DIR's README (rendered for
  PROJECT-ID over ISSUES), or nil when there's nothing to warn about."
  [issues-dir project-id issues]
  (case (store/index-state issues-dir)
    :missing {:kind :index-missing :severity :warning
              :msg "README.md is missing; run `issues init` to generate it"}
    :foreign {:kind :index-foreign :severity :warning
              :msg "README.md was not generated by issues and won't be updated"}
    :generated (let [path (str (fs/path issues-dir "README.md"))]
                 (when (not= (slurp path) (store/index-markdown project-id issues))
                   {:kind :index-stale :severity :warning
                    :msg "README.md is out of date; regenerate it"}))))

(defn read-project
  "Assemble the full picture of the project at `(:issues-dir project-ref)`:
  `{:id :path :issues-dir :issues :problems}`. Each issue in `:issues`
  gets `:project` and `:ref` added. `:problems` collects every issue's own
  problems (annotated with `:id`/`:file` when absent), then cross-issue
  problems from `store/dir-problems`, then one warning about the generated
  README's state when applicable."
  [{:keys [issues-dir]}]
  (let [id (project-id issues-dir)
        issues (mapv (fn [issue]
                       (assoc issue :project id :ref (issue/ref-string id (:id issue))))
                     (store/read-all issues-dir))
        issue-problems (mapcat (fn [issue]
                                 (map (partial annotate-problem issue) (:problems issue)))
                               issues)
        dir-problems (store/dir-problems issues)
        idx-problem (index-problem issues-dir id issues)]
    {:id id
     :path (str (fs/parent (fs/absolutize issues-dir)))
     :issues-dir issues-dir
     :issues issues
     :problems (vec (concat issue-problems dir-problems (when idx-problem [idx-problem])))}))
